// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Test$LearnReasonmlWorkshop = require("../../support/test.bs.js");

function add(coord1, coord2) {
  return Pervasives.failwith("For you to implement");
}

function first(pair) {
  return Pervasives.failwith("For you to implement");
}

function second(pair) {
  return Pervasives.failwith("For you to implement");
}

Test$LearnReasonmlWorkshop.runAll(/* :: */[
      /* tuple */[
        Caml_obj.caml_equal(Pervasives.failwith("For you to implement"), /* tuple */[
              4,
              6
            ]),
        "add"
      ],
      /* :: */[
        /* tuple */[
          Pervasives.failwith("For you to implement") === "foo",
          "first"
        ],
        /* :: */[
          /* tuple */[
            Pervasives.failwith("For you to implement") === /* "b" */98,
            "second"
          ],
          /* [] */0
        ]
      ]
    ]);

exports.add = add;
exports.first = first;
exports.second = second;
/*  Not a pure module */
