// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Test$LearnReasonmlWorkshop = require("../../support/test.bs.js");

function simplerLargest(xs) {
  return Pervasives.failwith("For you to implement");
}

function simplerSmallest(xs) {
  return Pervasives.failwith("For you to implement");
}

Test$LearnReasonmlWorkshop.runAll(/* :: */[
      /* tuple */[
        Pervasives.failwith("For you to implement") === Pervasives.infinity,
        "simpler smallest"
      ],
      /* :: */[
        /* tuple */[
          Pervasives.failwith("For you to implement") === 55,
          "simpler smallest"
        ],
        /* :: */[
          /* tuple */[
            Pervasives.failwith("For you to implement") === -5,
            "simpler smallest"
          ],
          /* :: */[
            /* tuple */[
              Pervasives.failwith("For you to implement") === 1,
              "simpler smallest"
            ],
            /* :: */[
              /* tuple */[
                Pervasives.failwith("For you to implement") === Pervasives.neg_infinity,
                "simpler largest"
              ],
              /* :: */[
                /* tuple */[
                  Pervasives.failwith("For you to implement") === 55,
                  "simpler largest"
                ],
                /* :: */[
                  /* tuple */[
                    Pervasives.failwith("For you to implement") === 5,
                    "simpler largest"
                  ],
                  /* :: */[
                    /* tuple */[
                      Pervasives.failwith("For you to implement") === 5,
                      "simpler largest"
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

exports.simplerLargest = simplerLargest;
exports.simplerSmallest = simplerSmallest;
/*  Not a pure module */
