// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Test$LearnReasonmlWorkshop = require("../../support/test.bs.js");

function plus(x, y) {
  return Pervasives.failwith("For you to implement");
}

function times(x, y) {
  return Pervasives.failwith("For you to implement");
}

function minus(x, y) {
  return Pervasives.failwith("For you to implement");
}

function divide(x, y) {
  return Pervasives.failwith("For you to implement");
}

Test$LearnReasonmlWorkshop.runAll(/* :: */[
      /* tuple */[
        Pervasives.failwith("For you to implement") === 2,
        "plus"
      ],
      /* :: */[
        /* tuple */[
          Pervasives.failwith("For you to implement") === 49,
          "plus"
        ],
        /* :: */[
          /* tuple */[
            Pervasives.failwith("For you to implement") === 64,
            "times"
          ],
          /* :: */[
            /* tuple */[
              Pervasives.failwith("For you to implement") === -2048,
              "times"
            ],
            /* :: */[
              /* tuple */[
                Pervasives.failwith("For you to implement") === -4,
                "minus"
              ],
              /* :: */[
                /* tuple */[
                  Pervasives.failwith("For you to implement") === 1000,
                  "minus"
                ],
                /* :: */[
                  /* tuple */[
                    Pervasives.failwith("For you to implement") === 512,
                    "divide"
                  ],
                  /* :: */[
                    /* tuple */[
                      Pervasives.failwith("For you to implement") === 1010,
                      "divide"
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

exports.plus = plus;
exports.times = times;
exports.minus = minus;
exports.divide = divide;
/*  Not a pure module */
