// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Test$LearnReasonmlWorkshop = require("../../support/test.bs.js");

function modulo(dividend, divisor) {
  return Pervasives.failwith("For you to implement");
}

Test$LearnReasonmlWorkshop.runAll(/* :: */[
      /* tuple */[
        Pervasives.failwith("For you to implement") === 2,
        "modulo"
      ],
      /* :: */[
        /* tuple */[
          Pervasives.failwith("For you to implement") === 0,
          "modulo"
        ],
        /* [] */0
      ]
    ]);

exports.modulo = modulo;
/*  Not a pure module */
