// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Test$LearnReasonmlWorkshop = require("../../support/test.bs.js");

function nonZero(x) {
  return Pervasives.failwith("For you to implement");
}

Test$LearnReasonmlWorkshop.runAll(/* :: */[
      /* tuple */[
        Pervasives.failwith("For you to implement") === false,
        "non zero"
      ],
      /* :: */[
        /* tuple */[
          Pervasives.failwith("For you to implement") === true,
          "non zero"
        ],
        /* :: */[
          /* tuple */[
            Pervasives.failwith("For you to implement") === true,
            "non zero"
          ],
          /* [] */0
        ]
      ]
    ]);

exports.nonZero = nonZero;
/*  Not a pure module */
