// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Test$LearnReasonmlWorkshop = require("../../support/test.bs.js");

function cardValueToScore(cardValue) {
  return Pervasives.failwith("For you to implement");
}

Test$LearnReasonmlWorkshop.runAll(/* :: */[
      /* tuple */[
        Pervasives.failwith("For you to implement") === 11,
        "card value to score"
      ],
      /* :: */[
        /* tuple */[
          Pervasives.failwith("For you to implement") === 10,
          "card value to score"
        ],
        /* :: */[
          /* tuple */[
            Pervasives.failwith("For you to implement") === 10,
            "card value to score"
          ],
          /* :: */[
            /* tuple */[
              Pervasives.failwith("For you to implement") === 10,
              "card value to score"
            ],
            /* :: */[
              /* tuple */[
                Pervasives.failwith("For you to implement") === 5,
                "card value to score"
              ],
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

exports.cardValueToScore = cardValueToScore;
/*  Not a pure module */
