// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Test$LearnReasonmlWorkshop = require("../../support/test.bs.js");

function sum(lst) {
  return Pervasives.failwith("For you to implement");
}

Test$LearnReasonmlWorkshop.runAll(/* :: */[
      /* tuple */[
        Pervasives.failwith("For you to implement") === 0,
        "sum"
      ],
      /* :: */[
        /* tuple */[
          Pervasives.failwith("For you to implement") === 55,
          "sum"
        ],
        /* :: */[
          /* tuple */[
            Pervasives.failwith("For you to implement") === 0,
            "sum"
          ],
          /* :: */[
            /* tuple */[
              Pervasives.failwith("For you to implement") === 12,
              "sum"
            ],
            /* [] */0
          ]
        ]
      ]
    ]);

exports.sum = sum;
/*  Not a pure module */
