// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var Test$LearnReasonmlWorkshop = require("../../support/test.bs.js");

function addOneToAge(person) {
  return {
          age: person.age + 1 | 0,
          firstName: person.firstName,
          lastName: person.lastName,
          numberOfCars: person.numberOfCars
        };
}

if (23 !== addOneToAge({
        age: 22,
        firstName: "Cotton-eyed",
        lastName: "Joe",
        numberOfCars: 0
      }).age) {
  throw [
        Caml_builtin_exceptions.assert_failure,
        /* tuple */[
          "records.re",
          58,
          9
        ]
      ];
}

function modifyPerson(person) {
  return Pervasives.failwith("For you to implement");
}

var test_ex1$prime = {
  age: 30,
  firstName: "Jan",
  lastName: "Saffer",
  numberOfCars: 0
};

var test_ex2$prime = {
  age: 4,
  firstName: "Hugo",
  lastName: "Heuzard",
  numberOfCars: 61
};

Test$LearnReasonmlWorkshop.runAll(/* :: */[
      /* tuple */[
        Caml_obj.caml_equal(Pervasives.failwith("For you to implement"), test_ex1$prime),
        "modifyPerson"
      ],
      /* :: */[
        /* tuple */[
          Caml_obj.caml_equal(Pervasives.failwith("For you to implement"), test_ex2$prime),
          "modifyPerson"
        ],
        /* [] */0
      ]
    ]);

exports.modifyPerson = modifyPerson;
/*  Not a pure module */
