// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Test$LearnReasonmlWorkshop = require("../../support/test.bs.js");

function simplerSum(xs) {
  return Pervasives.failwith("For you to implement");
}

function simplerProduct(xs) {
  return Pervasives.failwith("For you to implement");
}

Test$LearnReasonmlWorkshop.runAll(/* :: */[
      /* tuple */[
        Pervasives.failwith("For you to implement") === 1,
        "simpler product"
      ],
      /* :: */[
        /* tuple */[
          Pervasives.failwith("For you to implement") === 55,
          "simpler product"
        ],
        /* :: */[
          /* tuple */[
            Pervasives.failwith("For you to implement") === 25,
            "simpler product"
          ],
          /* :: */[
            /* tuple */[
              Pervasives.failwith("For you to implement") === 25,
              "simpler product"
            ],
            /* :: */[
              /* tuple */[
                Pervasives.failwith("For you to implement") === 0,
                "simpler sum"
              ],
              /* :: */[
                /* tuple */[
                  Pervasives.failwith("For you to implement") === 55,
                  "simpler sum"
                ],
                /* :: */[
                  /* tuple */[
                    Pervasives.failwith("For you to implement") === 0,
                    "simpler sum"
                  ],
                  /* :: */[
                    /* tuple */[
                      Pervasives.failwith("For you to implement") === 12,
                      "simpler sum"
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

exports.simplerSum = simplerSum;
exports.simplerProduct = simplerProduct;
/*  Not a pure module */
