// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Test$LearnReasonmlWorkshop = require("../../support/test.bs.js");

function intAverage(x, y) {
  return Pervasives.failwith("For you to implement");
}

function floatAverage(x, y) {
  return Pervasives.failwith("For you to implement");
}

var fullName = "Fred Flintstone";

console.log("Hi, My name is ");

console.log(fullName);

console.log(" and I am 5 years old");

Test$LearnReasonmlWorkshop.runAll(/* :: */[
      /* tuple */[
        Pervasives.failwith("For you to implement") === 5,
        "int average"
      ],
      /* :: */[
        /* tuple */[
          Pervasives.failwith("For you to implement") === 5,
          "float average"
        ],
        /* :: */[
          /* tuple */[
            Pervasives.failwith("For you to implement") === 7.5,
            "float average"
          ],
          /* [] */0
        ]
      ]
    ]);

exports.intAverage = intAverage;
exports.floatAverage = floatAverage;
/*  Not a pure module */
